version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: talk
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - service_network

  redis:
    image: redis:7.4.2
    container_name: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    networks:
      - service_network

volumes:
  mysql_volume:
  redis_volume:

networks:
  service_network:
    driver: bridge