server:
  port: 8081
  instanceId: 1
  servlet:
    session:
      cookie:
        name: JSESSIONID
  tomcat:
    max-connections: 65535

spring:
  profiles:
    default: prod
  application:
    name: chat-server
  jpa:
    open-in-view: false